class CoinData {
  final String name;
  final String icon;
  final String price;
  final String purity;
  final String weight;
  final String diameter;
  final String year;
  final String country;
  final String metal;

  CoinData({
    required this.name,
    required this.icon,
    required this.price,
    required this.purity,
    required this.weight,
    required this.diameter,
    required this.year,
    required this.country,
    required this.metal,
  });

  static List<CoinData> getAllCoins() {
    return [
      CoinData(name: 'American Gold Eagle', icon: '🦅', price: '\$2,100', purity: '91.67%', weight: '33.93g', diameter: '32.7mm', year: '2023', country: 'USA', metal: 'Gold'),
      CoinData(name: 'Canadian Maple Leaf', icon: '🍁', price: '\$2,050', purity: '99.99%', weight: '31.10g', diameter: '30mm', year: '2023', country: 'Canada', metal: 'Gold'),
      CoinData(name: 'South African Krugerrand', icon: '🌍', price: '\$1,950', purity: '91.67%', weight: '33.93g', diameter: '32.77mm', year: '2023', country: 'South Africa', metal: 'Gold'),
      CoinData(name: 'Austrian Philharmonic', icon: '🎵', price: '\$2,080', purity: '99.99%', weight: '31.10g', diameter: '37mm', year: '2023', country: 'Austria', metal: 'Gold'),
      CoinData(name: 'Chinese Gold Panda', icon: '🐼', price: '\$2,200', purity: '99.90%', weight: '30g', diameter: '32mm', year: '2023', country: 'China', metal: 'Gold'),
      CoinData(name: 'British Sovereign', icon: '👑', price: '\$520', purity: '91.67%', weight: '7.98g', diameter: '22.05mm', year: '2023', country: 'UK', metal: 'Gold'),
      CoinData(name: 'Australian Kangaroo', icon: '🦘', price: '\$2,070', purity: '99.99%', weight: '31.10g', diameter: '32.12mm', year: '2023', country: 'Australia', metal: 'Gold'),
      CoinData(name: 'American Silver Eagle', icon: '🦅', price: '\$32', purity: '99.90%', weight: '31.10g', diameter: '40.6mm', year: '2023', country: 'USA', metal: 'Silver'),
      CoinData(name: 'Canadian Silver Maple', icon: '🍁', price: '\$30', purity: '99.99%', weight: '31.10g', diameter: '38mm', year: '2023', country: 'Canada', metal: 'Silver'),
      CoinData(name: 'Mexican Libertad', icon: '🇲🇽', price: '\$35', purity: '99.90%', weight: '31.10g', diameter: '40mm', year: '2023', country: 'Mexico', metal: 'Silver'),
      CoinData(name: 'Austrian Silver Philharmonic', icon: '🎵', price: '\$31', purity: '99.90%', weight: '31.10g', diameter: '37mm', year: '2023', country: 'Austria', metal: 'Silver'),
      CoinData(name: 'British Britannia Silver', icon: '👑', price: '\$33', purity: '99.90%', weight: '31.10g', diameter: '38.61mm', year: '2023', country: 'UK', metal: 'Silver'),
      CoinData(name: 'Australian Kookaburra', icon: '🦜', price: '\$34', purity: '99.99%', weight: '31.10g', diameter: '40.6mm', year: '2023', country: 'Australia', metal: 'Silver'),
      CoinData(name: 'Morgan Silver Dollar', icon: '💵', price: '\$45', purity: '90%', weight: '26.73g', diameter: '38.1mm', year: '1921', country: 'USA', metal: 'Silver'),
      CoinData(name: 'Peace Silver Dollar', icon: '🕊️', price: '\$42', purity: '90%', weight: '26.73g', diameter: '38.1mm', year: '1935', country: 'USA', metal: 'Silver'),
      CoinData(name: 'Walking Liberty Half', icon: '🚶', price: '\$18', purity: '90%', weight: '12.50g', diameter: '30.6mm', year: '1947', country: 'USA', metal: 'Silver'),
      CoinData(name: 'Mercury Dime', icon: '💫', price: '\$4', purity: '90%', weight: '2.50g', diameter: '17.9mm', year: '1945', country: 'USA', metal: 'Silver'),
      CoinData(name: 'Buffalo Nickel', icon: '🦬', price: '\$2', purity: '75%', weight: '5g', diameter: '21.2mm', year: '1937', country: 'USA', metal: 'Nickel'),
      CoinData(name: 'Indian Head Penny', icon: '🪶', price: '\$3', purity: '95%', weight: '3.11g', diameter: '19mm', year: '1909', country: 'USA', metal: 'Copper'),
      CoinData(name: 'Lincoln Wheat Penny', icon: '🌾', price: '\$0.50', purity: '95%', weight: '3.11g', diameter: '19mm', year: '1958', country: 'USA', metal: 'Copper'),
      CoinData(name: 'Roman Denarius', icon: '🏛️', price: '\$150', purity: '95%', weight: '3.90g', diameter: '18mm', year: '100 AD', country: 'Rome', metal: 'Silver'),
      CoinData(name: 'Greek Drachma', icon: '🏺', price: '\$200', purity: '98%', weight: '4.30g', diameter: '17mm', year: '400 BC', country: 'Greece', metal: 'Silver'),
      CoinData(name: 'Byzantine Solidus', icon: '⚜️', price: '\$800', purity: '99%', weight: '4.50g', diameter: '20mm', year: '600 AD', country: 'Byzantine', metal: 'Gold'),
      CoinData(name: 'Spanish Doubloon', icon: '⚓', price: '\$5,000', purity: '91%', weight: '6.77g', diameter: '22mm', year: '1715', country: 'Spain', metal: 'Gold'),
      CoinData(name: 'French Napoleon', icon: '🇫🇷', price: '\$450', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1812', country: 'France', metal: 'Gold'),
      CoinData(name: 'German Mark', icon: '🇩🇪', price: '\$15', purity: '90%', weight: '5.55g', diameter: '23mm', year: '1914', country: 'Germany', metal: 'Silver'),
      CoinData(name: 'Swiss Franc', icon: '🇨🇭', price: '\$450', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1935', country: 'Switzerland', metal: 'Gold'),
      CoinData(name: 'Japanese Yen', icon: '🇯🇵', price: '\$800', purity: '90%', weight: '8.33g', diameter: '23mm', year: '1870', country: 'Japan', metal: 'Gold'),
      CoinData(name: 'Russian Ruble', icon: '🇷🇺', price: '\$350', purity: '90%', weight: '6.45g', diameter: '22mm', year: '1899', country: 'Russia', metal: 'Gold'),
      CoinData(name: 'Indian Rupee', icon: '🇮🇳', price: '\$25', purity: '91.67%', weight: '11.66g', diameter: '30mm', year: '1947', country: 'India', metal: 'Silver'),
      CoinData(name: 'Dutch Guilder', icon: '🇳🇱', price: '\$400', purity: '90%', weight: '6.72g', diameter: '22mm', year: '1875', country: 'Netherlands', metal: 'Gold'),
      CoinData(name: 'Italian Lira', icon: '🇮🇹', price: '\$380', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1910', country: 'Italy', metal: 'Gold'),
      CoinData(name: 'Portuguese Escudo', icon: '🇵🇹', price: '\$420', purity: '91.67%', weight: '7.32g', diameter: '22mm', year: '1920', country: 'Portugal', metal: 'Gold'),
      CoinData(name: 'Belgian Franc', icon: '🇧🇪', price: '\$390', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1914', country: 'Belgium', metal: 'Gold'),
      CoinData(name: 'Swedish Krona', icon: '🇸🇪', price: '\$410', purity: '90%', weight: '8.96g', diameter: '23mm', year: '1901', country: 'Sweden', metal: 'Gold'),
      CoinData(name: 'Norwegian Krone', icon: '🇳🇴', price: '\$400', purity: '90%', weight: '8.96g', diameter: '23mm', year: '1910', country: 'Norway', metal: 'Gold'),
      CoinData(name: 'Danish Krone', icon: '🇩🇰', price: '\$405', purity: '90%', weight: '8.96g', diameter: '23mm', year: '1908', country: 'Denmark', metal: 'Gold'),
      CoinData(name: 'Turkish Lira', icon: '🇹🇷', price: '\$350', purity: '91.67%', weight: '7.21g', diameter: '22mm', year: '1923', country: 'Turkey', metal: 'Gold'),
      CoinData(name: 'Egyptian Pound', icon: '🇪🇬', price: '\$450', purity: '91.67%', weight: '8.50g', diameter: '23mm', year: '1955', country: 'Egypt', metal: 'Gold'),
      CoinData(name: 'Israeli Shekel', icon: '🇮🇱', price: '\$380', purity: '90%', weight: '7g', diameter: '22mm', year: '1960', country: 'Israel', metal: 'Gold'),
      CoinData(name: 'Saudi Riyal', icon: '🇸🇦', price: '\$420', purity: '91.67%', weight: '7.98g', diameter: '22mm', year: '1950', country: 'Saudi Arabia', metal: 'Gold'),
      CoinData(name: 'UAE Dirham', icon: '🇦🇪', price: '\$400', purity: '91.67%', weight: '8g', diameter: '22mm', year: '1980', country: 'UAE', metal: 'Gold'),
      CoinData(name: 'Kuwaiti Dinar', icon: '🇰🇼', price: '\$450', purity: '91.67%', weight: '8.50g', diameter: '23mm', year: '1970', country: 'Kuwait', metal: 'Gold'),
      CoinData(name: 'Brazilian Real', icon: '🇧🇷', price: '\$380', purity: '90%', weight: '8.96g', diameter: '23mm', year: '1995', country: 'Brazil', metal: 'Gold'),
      CoinData(name: 'Argentine Peso', icon: '🇦🇷', price: '\$370', purity: '90%', weight: '8.06g', diameter: '22mm', year: '1881', country: 'Argentina', metal: 'Gold'),
      CoinData(name: 'Chilean Peso', icon: '🇨🇱', price: '\$360', purity: '90%', weight: '9.07g', diameter: '23mm', year: '1926', country: 'Chile', metal: 'Gold'),
      CoinData(name: 'Colombian Peso', icon: '🇨🇴', price: '\$350', purity: '91.67%', weight: '7.98g', diameter: '22mm', year: '1919', country: 'Colombia', metal: 'Gold'),
      CoinData(name: 'Peruvian Sol', icon: '🇵🇪', price: '\$380', purity: '90%', weight: '7.98g', diameter: '22mm', year: '1930', country: 'Peru', metal: 'Gold'),
      CoinData(name: 'Venezuelan Bolivar', icon: '🇻🇪', price: '\$340', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1912', country: 'Venezuela', metal: 'Gold'),
      CoinData(name: 'Cuban Peso', icon: '🇨🇺', price: '\$400', purity: '90%', weight: '8.35g', diameter: '23mm', year: '1915', country: 'Cuba', metal: 'Gold'),
      CoinData(name: 'Dominican Peso', icon: '🇩🇴', price: '\$350', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1955', country: 'Dominican Rep', metal: 'Gold'),
      CoinData(name: 'Costa Rican Colon', icon: '🇨🇷', price: '\$360', purity: '90%', weight: '6.72g', diameter: '22mm', year: '1897', country: 'Costa Rica', metal: 'Gold'),
      CoinData(name: 'Panamanian Balboa', icon: '🇵🇦', price: '\$370', purity: '90%', weight: '7.52g', diameter: '22mm', year: '1947', country: 'Panama', metal: 'Gold'),
      CoinData(name: 'Guatemalan Quetzal', icon: '🇬🇹', price: '\$340', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1926', country: 'Guatemala', metal: 'Gold'),
      CoinData(name: 'Honduran Lempira', icon: '🇭🇳', price: '\$330', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1931', country: 'Honduras', metal: 'Gold'),
      CoinData(name: 'Nicaraguan Cordoba', icon: '🇳🇮', price: '\$320', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1912', country: 'Nicaragua', metal: 'Gold'),
      CoinData(name: 'Salvadoran Colon', icon: '🇸🇻', price: '\$310', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1925', country: 'El Salvador', metal: 'Gold'),
      CoinData(name: 'Thai Baht', icon: '🇹🇭', price: '\$380', purity: '90%', weight: '7.50g', diameter: '22mm', year: '1908', country: 'Thailand', metal: 'Gold'),
      CoinData(name: 'Vietnamese Dong', icon: '🇻🇳', price: '\$300', purity: '90%', weight: '6g', diameter: '21mm', year: '1945', country: 'Vietnam', metal: 'Gold'),
      CoinData(name: 'Malaysian Ringgit', icon: '🇲🇾', price: '\$360', purity: '91.67%', weight: '7.32g', diameter: '22mm', year: '1971', country: 'Malaysia', metal: 'Gold'),
      CoinData(name: 'Singapore Dollar', icon: '🇸🇬', price: '\$400', purity: '91.67%', weight: '7.98g', diameter: '22mm', year: '1969', country: 'Singapore', metal: 'Gold'),
      CoinData(name: 'Indonesian Rupiah', icon: '🇮🇩', price: '\$340', purity: '90%', weight: '6.72g', diameter: '22mm', year: '1970', country: 'Indonesia', metal: 'Gold'),
      CoinData(name: 'Philippine Peso', icon: '🇵🇭', price: '\$350', purity: '90%', weight: '6.72g', diameter: '22mm', year: '1947', country: 'Philippines', metal: 'Gold'),
      CoinData(name: 'Korean Won', icon: '🇰🇷', price: '\$380', purity: '90%', weight: '7.50g', diameter: '22mm', year: '1970', country: 'South Korea', metal: 'Gold'),
      CoinData(name: 'Taiwanese Dollar', icon: '🇹🇼', price: '\$370', purity: '90%', weight: '7.32g', diameter: '22mm', year: '1965', country: 'Taiwan', metal: 'Gold'),
      CoinData(name: 'Hong Kong Dollar', icon: '🇭🇰', price: '\$390', purity: '91.67%', weight: '7.98g', diameter: '22mm', year: '1975', country: 'Hong Kong', metal: 'Gold'),
      CoinData(name: 'New Zealand Dollar', icon: '🇳🇿', price: '\$2,060', purity: '99.99%', weight: '31.10g', diameter: '32mm', year: '2023', country: 'New Zealand', metal: 'Gold'),
      CoinData(name: 'Fijian Dollar', icon: '🇫🇯', price: '\$350', purity: '90%', weight: '6.72g', diameter: '22mm', year: '1969', country: 'Fiji', metal: 'Gold'),
      CoinData(name: 'Samoan Tala', icon: '🇼🇸', price: '\$320', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1967', country: 'Samoa', metal: 'Gold'),
      CoinData(name: 'Tongan Paanga', icon: '🇹🇴', price: '\$310', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1967', country: 'Tonga', metal: 'Gold'),
      CoinData(name: 'Papua New Guinea Kina', icon: '🇵🇬', price: '\$340', purity: '90%', weight: '6.72g', diameter: '22mm', year: '1975', country: 'Papua New Guinea', metal: 'Gold'),
      CoinData(name: 'Vanuatu Vatu', icon: '🇻🇺', price: '\$300', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1980', country: 'Vanuatu', metal: 'Gold'),
      CoinData(name: 'Solomon Islands Dollar', icon: '🇸🇧', price: '\$290', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1977', country: 'Solomon Islands', metal: 'Gold'),
      CoinData(name: 'Kenyan Shilling', icon: '🇰🇪', price: '\$320', purity: '90%', weight: '6.72g', diameter: '22mm', year: '1966', country: 'Kenya', metal: 'Gold'),
      CoinData(name: 'Tanzanian Shilling', icon: '🇹🇿', price: '\$310', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1966', country: 'Tanzania', metal: 'Gold'),
      CoinData(name: 'Ugandan Shilling', icon: '🇺🇬', price: '\$300', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1966', country: 'Uganda', metal: 'Gold'),
      CoinData(name: 'Nigerian Naira', icon: '🇳🇬', price: '\$330', purity: '90%', weight: '6.72g', diameter: '22mm', year: '1973', country: 'Nigeria', metal: 'Gold'),
      CoinData(name: 'Ghanaian Cedi', icon: '🇬🇭', price: '\$320', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1965', country: 'Ghana', metal: 'Gold'),
      CoinData(name: 'Moroccan Dirham', icon: '🇲🇦', price: '\$340', purity: '90%', weight: '6.72g', diameter: '22mm', year: '1960', country: 'Morocco', metal: 'Gold'),
      CoinData(name: 'Algerian Dinar', icon: '🇩🇿', price: '\$330', purity: '90%', weight: '6.72g', diameter: '22mm', year: '1964', country: 'Algeria', metal: 'Gold'),
      CoinData(name: 'Tunisian Dinar', icon: '🇹🇳', price: '\$350', purity: '90%', weight: '6.72g', diameter: '22mm', year: '1960', country: 'Tunisia', metal: 'Gold'),
      CoinData(name: 'Libyan Dinar', icon: '🇱🇾', price: '\$360', purity: '90%', weight: '7.32g', diameter: '22mm', year: '1952', country: 'Libya', metal: 'Gold'),
      CoinData(name: 'Ethiopian Birr', icon: '🇪🇹', price: '\$310', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1944', country: 'Ethiopia', metal: 'Gold'),
      CoinData(name: 'Zambian Kwacha', icon: '🇿🇲', price: '\$300', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1968', country: 'Zambia', metal: 'Gold'),
      CoinData(name: 'Zimbabwean Dollar', icon: '🇿🇼', price: '\$290', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1980', country: 'Zimbabwe', metal: 'Gold'),
      CoinData(name: 'Botswana Pula', icon: '🇧🇼', price: '\$320', purity: '90%', weight: '6.72g', diameter: '22mm', year: '1976', country: 'Botswana', metal: 'Gold'),
      CoinData(name: 'Namibian Dollar', icon: '🇳🇦', price: '\$310', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1993', country: 'Namibia', metal: 'Gold'),
      CoinData(name: 'Angolan Kwanza', icon: '🇦🇴', price: '\$300', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1977', country: 'Angola', metal: 'Gold'),
      CoinData(name: 'Mozambican Metical', icon: '🇲🇿', price: '\$290', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1980', country: 'Mozambique', metal: 'Gold'),
      CoinData(name: 'Mauritian Rupee', icon: '🇲🇺', price: '\$330', purity: '90%', weight: '6.72g', diameter: '22mm', year: '1987', country: 'Mauritius', metal: 'Gold'),
      CoinData(name: 'Seychellois Rupee', icon: '🇸🇨', price: '\$320', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1976', country: 'Seychelles', metal: 'Gold'),
      CoinData(name: 'Malagasy Ariary', icon: '🇲🇬', price: '\$300', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1965', country: 'Madagascar', metal: 'Gold'),
      CoinData(name: 'Rwandan Franc', icon: '🇷🇼', price: '\$290', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1964', country: 'Rwanda', metal: 'Gold'),
      CoinData(name: 'Burundian Franc', icon: '🇧🇮', price: '\$280', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1965', country: 'Burundi', metal: 'Gold'),
      CoinData(name: 'Djiboutian Franc', icon: '🇩🇯', price: '\$290', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1977', country: 'Djibouti', metal: 'Gold'),
      CoinData(name: 'Somali Shilling', icon: '🇸🇴', price: '\$280', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1960', country: 'Somalia', metal: 'Gold'),
      CoinData(name: 'Eritrean Nakfa', icon: '🇪🇷', price: '\$270', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1997', country: 'Eritrea', metal: 'Gold'),
      CoinData(name: 'Sudanese Pound', icon: '🇸🇩', price: '\$300', purity: '90%', weight: '6.72g', diameter: '22mm', year: '1956', country: 'Sudan', metal: 'Gold'),
      CoinData(name: 'South Sudanese Pound', icon: '🇸🇸', price: '\$290', purity: '90%', weight: '6.45g', diameter: '21mm', year: '2011', country: 'South Sudan', metal: 'Gold'),
      CoinData(name: 'Lesotho Loti', icon: '🇱🇸', price: '\$280', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1980', country: 'Lesotho', metal: 'Gold'),
      CoinData(name: 'Swazi Lilangeni', icon: '🇸🇿', price: '\$290', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1974', country: 'Eswatini', metal: 'Gold'),
      CoinData(name: 'Malawian Kwacha', icon: '🇲🇼', price: '\$270', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1971', country: 'Malawi', metal: 'Gold'),
      CoinData(name: 'Congolese Franc', icon: '🇨🇩', price: '\$280', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1997', country: 'DR Congo', metal: 'Gold'),
      CoinData(name: 'Central African CFA', icon: '🇨🇫', price: '\$290', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1960', country: 'Central Africa', metal: 'Gold'),
      CoinData(name: 'West African CFA', icon: '🌍', price: '\$290', purity: '90%', weight: '6.45g', diameter: '21mm', year: '1945', country: 'West Africa', metal: 'Gold'),
    ];
  }
}
